### ISSUE TITLE
Incorrect comment indentation inside switch statements

### ISSUE THREAD

**Issue by Zopsss** [google/google-java-format#1147] opened 2024-08-22 10:42 UTC
Detected at @Checkstyle: https://github.com/checkstyle/checkstyle/pull/15521#issuecomment-2300045772

We were working on improving Checkstyle's test cases for google style guide. We used google-java-format tool to format the input file and used [google_checks.xml](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml) against it to ensure that we're following every rules. We had a case like:

```java
    switch (a) {
      // comment
      case 1:
      default:
    }
```

formatter formatted it to something like:

```java
    switch (a) {
        // comment
      case 1:
      default:
    }
```

the indentation for `// comment` increased, our test started failing and the violation message was:

```
764:9: Comment has incorrect indentation level 8, expected is 6, indentation should be the same level as line 765.
```

We faced this problem at 3 places in our input file, here's the full test result: https://github.com/checkstyle/checkstyle/pull/15521#issuecomment-2299323787

Based on [4.8.4.1 Indentation](https://google.github.io/styleguide/javaguide.html#s4.8.4.1-switch-indentation) & [4.2 Block indentation: +2 spaces](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation), the content should be increased by 2 spaces but formatter increased the indentation by 4 spaces.

**Comment by cushon** [comment] 2024-08-24 00:03
This is a duplicate of https://github.com/google/google-java-format/issues/1127, which is fixed at head and will be included in the next release

**Closed by cushon** 2024-08-24 00:03 UTC
