### ISSUE TITLE
Please provide Eclipse plugin in version 1.7

### ISSUE THREAD

**Issue by PhilippWendler** [google/google-java-format#331] opened 2019-01-10 14:38 UTC
The [release page for version 1.7](https://github.com/google/google-java-format/releases/tag/google-java-format-1.7) does not contain an Eclipse plugin like the previous versions. The [readme](https://github.com/google/google-java-format#eclipse) still mentions that page as the download source of the Eclipse plugin.

So please provide a JAR with the Eclipse plugin as part of the relase.

**Comment by arifogel** [comment] 2019-01-18 20:59
I was able to build by following:
https://github.com/google/google-java-format/issues/190
https://github.com/google/google-java-format/blob/master/eclipse_plugin/README.md

My steps (use attached diff):
```
git clone https://github.com/google/google-java-format
cd google-java-format
git checkout google-java-format-1.7
git apply < build-ecliipse-plugin-from-release-1.7.diff.txt
mvn install ### THIS STEP IS SUPPOSED TO FAIL
```
Then follow [eclipse plugin build instructions](https://github.com/google/google-java-format/blob/master/eclipse_plugin/README.md) starting at step 2.


[build-ecliipse-plugin-from-release-1.7.diff.txt](https://github.com/google/google-java-format/files/2774485/build-ecliipse-plugin-from-release-1.7.diff.txt)

**Comment by arifogel** [comment] 2019-01-18 21:01
I've attached a build using above instructions for convenience.
[google-java-format-eclipse-plugin-1.7.0.jar.zip](https://github.com/google/google-java-format/files/2774507/google-java-format-eclipse-plugin-1.7.0.jar.zip)

**Comment by PhilippWendler** [comment] 2019-01-22 06:39
Please provide an *official* build in the GitHub release. I would like to be able to tell our project contributors to go there and download it.

**Comment by wacaine** [comment] 2019-05-30 17:31
The attached unofficial build for 1.7 above does not work when I attempt to install it in eclipse.  eclipse does not appear to recognize it at all.  When I tried the provided steps to reproduce I get a compile error

`$ mvn install
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: com.google.googlejavaformat:google-java-format-eclipse-plugin:1.7.0 @ /Users/wac84s/Downloads/google-java-format-master/eclipse_plugin/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/
[INFO] Adding repository http://download.eclipse.org/releases/mars
[INFO] Fetching p2.index from http://download.eclipse.org/technology/epp/packages/mars/
[INFO] Fetching p2.index from http://download.eclipse.org/technology/epp/packages/mars/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201506241002/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201506241002/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201510021000/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201510021000/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201602261000/
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201602261000/
[INFO] Resolving dependencies of MavenProject: com.google.googlejavaformat:google-java-format-eclipse-plugin:1.7.0 @ /Users/wac84s/Downloads/google-java-format-master/eclipse_plugin/pom.xml
[INFO] Resolving class path of MavenProject: com.google.googlejavaformat:google-java-format-eclipse-plugin:1.7.0 @ /Users/wac84s/Downloads/google-java-format-master/eclipse_plugin/pom.xml
[INFO] 
[INFO] ---< com.google.googlejavaformat:google-java-format-eclipse-plugin >----
[INFO] Building google-java-format Plugin for Eclipse 4.5+ 1.7.0
[INFO] ---------------------------[ eclipse-plugin ]---------------------------
[INFO] 
[INFO] --- tycho-packaging-plugin:0.26.0:build-qualifier (default-build-qualifier) @ google-java-format-eclipse-plugin ---
[INFO] The project's OSGi version is 1.7.0
[INFO] 
[INFO] --- tycho-packaging-plugin:0.26.0:validate-id (default-validate-id) @ google-java-format-eclipse-plugin ---
[INFO] 
[INFO] --- tycho-packaging-plugin:0.26.0:validate-version (default-validate-version) @ google-java-format-eclipse-plugin ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ google-java-format-eclipse-plugin ---
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ google-java-format-eclipse-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/wac84s/Downloads/google-java-format-master/eclipse_plugin/src/main/resources
[INFO] 
[INFO] --- tycho-compiler-plugin:0.26.0:compile (default-compile) @ google-java-format-eclipse-plugin ---
[INFO] Compiling 1 source file to /Users/wac84s/Downloads/google-java-format-master/eclipse_plugin/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.584 s
[INFO] Finished at: 2019-05-30T13:29:21-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.26.0:compile (default-compile) on project google-java-format-eclipse-plugin: Compilation failure: Compilation failure: 
[ERROR] /Users/wac84s/Downloads/google-java-format-master/eclipse_plugin/src/com/google/googlejavaformat/java/GoogleJavaFormatter.java:[17] 
[ERROR] 	import com.google.common.base.Preconditions;
[ERROR] 	       ^^^^^^^^^^^^^^^^^
[ERROR] The import com.google.common cannot be resolved
[ERROR] /Users/wac84s/Downloads/google-java-format-master/eclipse_plugin/src/com/google/googlejavaformat/java/GoogleJavaFormatter.java:[18] 
[ERROR] 	import com.google.common.collect.Range;
[ERROR] 	       ^^^^^^^^^^^^^^^^^
...... truncted list. it is as if it does not see guava on classpath
`

**Comment by arifogel** [comment] 2019-05-30 17:37
From the above instructions:
> mvn install ### THIS STEP IS SUPPOSED TO FAIL

Did you follow up that step with:
> Then follow [eclipse plugin build instructions](https://github.com/google/google-java-format/blob/master/eclipse_plugin/README.md) starting at step 2.

as indicated in that comment?

**Comment by arifogel** [comment] 2019-05-30 17:39
Also @wacaine this might be a stupid question, but did you unzip the jar first before placing the jar in the `dropins` folder?

**Comment by arifogel** [comment] 2019-05-30 17:43
I mean, did you unzip the jar out of the attached zip? I had to pack the jar inside a zip because of github file posting rules.
```
$ unzip -t google-java-format-eclipse-plugin-1.7.0.jar.zip 
Archive:  google-java-format-eclipse-plugin-1.7.0.jar.zip
    testing: plugins/                 OK
    testing: plugins/google-java-format-eclipse-plugin_1.7.0.jar   OK
No errors detected in compressed data of google-java-format-eclipse-plugin-1.7.0.jar.zip.
```
You need to put the `plugins/google-java-format-eclipse-plugin_1.7.0.jar` file in the eclipse `dropins` folder.

**Comment by wacaine** [comment] 2019-05-30 20:55
I unzipped and put in drop ins.  It works for 1.6 (official download).  Does not work for 1.7 unofficial download.  I unzipped the file and placed the jar in correct place and restarted eclipse in-between.  See attached screenshot.  I am using eclipse oxygen3.a.
![side-by-side](https://user-images.githubusercontent.com/2999141/58663974-acdbd100-82fb-11e9-836f-d4f641f41f62.png)

**Comment by arifogel** [comment] 2019-05-30 21:10
@wacaine  I believe I built it with a later version than oxygen. I would suggest attempting to complete the build on your older version of eclipse as instructed above, and seeing if that produces a usable output jar.

**Comment by wacaine** [comment] 2019-05-31 13:13
@arifogel See my earlier post above with the output from the mvn install . It throws a ton of compiler errors not being able to find classes (missing guava classes).  When I check the target folder no jar was built (because of the compile time issues).  

org.eclipse.tycho:tycho-compiler-plugin:0.26.0:compile (default-compile) on project google-java-format-eclipse-plugin: Compilation failure: Compilation failure

I am not familiar with Tycho and how it resolves classpaths.  Any suggestions or reference materials you can point me at?  I am not clear on how to build against a different version of eclipse.  From what I see it builds against the Eclipse Mars release which is older than Oxygen


![Screen Shot 2019-05-31 at 9 08 36 AM](https://user-images.githubusercontent.com/2999141/58707911-418a1180-8384-11e9-9b85-63c1f1145af2.png)

**Comment by DanVanAtta** [comment] 2019-08-22 23:54
Custom building an eclipse plugin does not seem to be a really good long term solution and also goes against the goal of having a simple formatter that an entire team can install and then not worry about. Just encountered this problem and found out it's a version issue.

The [README instructions](https://github.com/google/google-java-format) for installing goole java formatter are not consistent with itself, it has [1.7 dependencies](https://github.com/google/google-java-format#from-the-command-line) yet the [eclipse plugin](https://github.com/google/google-java-format#eclipse) is 1.6 

Out of the box the intellij plugin and gradle plugin spotless use 1.7, which clashes with 1.6. I'd suggest it's really important then for the eclipse plugin to reach parity to avoid a problem of differing formatters. 

Is there an ETA for when the eclipse 1.7 plugin would be available and the readme instructions updated?

**Comment by ddellspe** [comment] 2019-11-13 14:06
of note, because I know it might help others after I dropped the `.jar` into my dropins folder, I still didn't ever see the items, even after eclipse and machine restart.  when I ran eclipse via command line with `eclipse -clean` that made it show up.

**Comment by PhilippWendler** [comment] 2020-01-14 15:25
The 1.7 release is now *more than one year old*, and there is still no build of the Eclipse plugin available.

Please provide an official build of the plugin or tell us if you will never do so such that we can look for alternate solutions (and remove the outdated plugin link from the readme in this case).

**Comment by av1m** [comment] 2020-05-23 21:53
Release 1.8 is out and I encountered the same problem when I ran a test (CLI, IntelliJ, Idea).
(By the time I find that the problem came from the version ...)
Has anyone found a solution to benefit from google-java-format 1.8 on eclipse?

**Comment by jan-z** [comment] 2020-06-07 07:52
For the impatient: [google-java-format-eclipse-plugin-1.8.0.jar.zip](https://github.com/google/google-java-format/files/4741535/google-java-format-eclipse-plugin-1.8.0.jar.zip) is a build (using JDK14) of version 1.8.0, created out of this pull request: https://github.com/google/google-java-format/pull/465. 

Unzip the zip file and put the jar file into the dropins folder. Works fine for me on Eclipse 2020-03.

**Comment by oliviercailloux** [comment] 2020-07-14 15:48
@avim did you find a satisfactory solution for using Eclipse together with google style? I suppose your team used some Eclipse plugin together with the `coveooss:fmt-maven-plugin` in your [own project](https://github.com/av1m/Apartments/): what did you use and what was your experience with this? What would you recommend? The build referenced here above, or something else?

**Comment by av1m** [comment] 2020-07-14 17:09
I was waiting for the Eclipse plugin. The latest current version of the Eclipse plugin is 1.6. 
The latest version of `google-java-format` is 1.8 (so the name of the issue already seems to be obsolete)
However, PR #465 is still pending merger and should resolve this issue.

Not being able to use the `google-java-format` version for Eclipse, I was able to use workarounds. 
I give you my feedback. I try :
- [Google Actions](https://github.com/axel-op/googlejavaformat-action): At each event (described in our configuration file), we check that the code is well formatted. If not, a bot will execute google-java-format and commit. This is a very good way to do it and allow a team to work on files that are necessarily formatted but cause an increase in commits (and the need to do `git fetch`). In addition, developers don't even have to use `google-java-format` locally.
- The coveooss plugin: [fmt-maven-plugin](https://github.com/coveooss/fmt-maven-plugin) also works very well: It allows you to execute `google-java-format` by integrating into maven, so at each once we make a maven command, `google-java-format` is called. However, I was able to raise two constraints.
  - When a new release of `google-java-format` comes out, you have to wait for the update of `fmt-maven-plugin`
  - We don't always think about launching a maven command (if our IDE already does the work without going through maven)
- Use a [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks): before each commit (for example), `google-java-format` is automatically called. Very practical because we directly control the version of `google-java-format` using the jar
- A somewhat technical solution: place the [jar](https://github.com/google/google-java-format/releases/download/google-java-format-1.8/google-java-format-1.8-all-deps.jar) (with all the dependencies) and use a script that executes `google-java-format` (in the project you want). A defect is that you have to remember to execute the script ...

Using git hooks is the most efficient way for me to work. We forget that we are using `google-java-format`

I also wrote a small note on this [repository](https://github.com/av1m/Apartments/tree/90b9e78d1494179db9622ab0e53344805a028749#code-style-). It generally resumes what is written in the [official repository](https://github.com/google/google-java-format#google-java-format).

I hope you are satisfied with this answer. cc @oliviercailloux

**Comment by oliviercailloux** [comment] 2020-07-14 17:25
Thanks a lot.

FTR (and in order to argue for the usefulness of the corresponding PR), none of these solutions seem great to me. I don’t like anything to re-format automatically behind the scenes; I think the re-format should be done where I code, and in such a way that I can see its consequences (e.g., in case something goes wrong, I can see it and act) before me committing. I also don’t want to force developers (or myself) to think about running maven “manually” (meaning, in a way that is not integrated in the IDE) on a regular basis. As a consequence, I want some integration within Eclipse itself.

`coveooss:fmt-maven-plugin` is great but I’d use it only for checking that everything is properly formatted, for the above reason.

I guess I’ll wait that the corresponding PR gets merged, as I am not impatient enough to use a non-official build as proposed here above.

**Comment by ativ97** [comment] 2020-08-12 16:40
> For the impatient: [google-java-format-eclipse-plugin-1.8.0.jar.zip](https://github.com/google/google-java-format/files/4741535/google-java-format-eclipse-plugin-1.8.0.jar.zip) is a build (using JDK14) of version 1.8.0, created out of this pull request: #465.
> 
> Unzip the zip file and put the jar file into the dropins folder. Works fine for me on Eclipse 2020-03.

Hey, So some of my team members are running the intellij plugin but I am using eclipse so I tried to use the jar file you provided. I am facing some issues trying to get this to work. I dropped in the jar file in the drop ins folder and did a `eclipse -clean` but the plug-in still was not showing up. So i opened an OSGi console and ran `ss` and I saw that the plug-in was installed but now resolved. After running the `diag` command in the console i get the following error-

`osgi> diag 649
  google-java-format-eclipse-plugin [649]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"`

![image](https://user-images.githubusercontent.com/17281663/90042265-11c8e000-dc90-11ea-8f30-1b6075a1acd3.png)


The project I am trying to use the plug-in on, uses java 1.8 and I saw jdk 11 mentioned somewhere. Does this means that the plug-in won't be supported for projects below jdk 11 from now on. I thought that didn't make sense as my other team members on intellij are working on the same project as me and for them the plug-in works fine.

Any help will be appreciated!

**Comment by Stephan202** [comment] 2020-08-12 17:02
@ativ97 indeed, as the release notes for GJF 1.8 [indicate](https://github.com/google/google-java-format/releases/tag/google-java-format-1.8) the minimum supported runtime version is now JDK 11. Note that this means that the IDE/plugin needs to run on JDK 11, but the code base being formatted can target an earlier Java version.

**Comment by aaiezza** [comment] 2020-09-28 21:02
> For the impatient: google-java-format-eclipse-plugin-1.8.0.jar.zip is a build (using JDK14) of version 1.8.0, created out of this pull request: #465.

> Unzip the zip file and put the jar file into the dropins folder. Works fine for me on Eclipse 2020-03.

This doesn't seem to work for 2020-09.
I would love it if the eclipse plugin worked the same as the coveo format maven plugin though! There are some slight differences in the output, and I'm assuming that bumping to version 1.8.0 will fix it.

**Comment by sarguin-lacapitale** [comment] 2021-03-04 17:32
Please provide Eclipse plugin in version 1.9

**Comment by PhilippWendler** [comment] 2021-08-02 12:19
Big thanks @cushon for building and uploading [version 1.11.0 of the Eclipse plugin](https://github.com/google/google-java-format/releases/tag/v1.11.0)!

This resolves this issue, but you might want to update the link to the Eclipse plugin in the [README](https://github.com/google/google-java-format#eclipse)?

**Comment by av1m** [comment] 2021-08-02 12:30
@PhilippWendler check #639

**Comment by cushon** [comment] 2021-08-02 17:05
https://github.com/google/google-java-format/releases/tag/v1.11.0

**Closed by cushon** 2021-08-02 17:05 UTC
Labels: Eclipse
