### ISSUE TITLE
Braces should be always used

### ISSUE THREAD

**Issue by chulkilee** [google/google-java-format#610] opened 2021-05-26 14:54 UTC
https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

> Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement.

And the intellij code schema xml has the settings for this. However, google-java-format jar (1.10.0) and intellij plugin 1.9.0.1
 does not correctly do that.

If I disabled the intellij plugin (which overrides the code style format), then intellij forces braces correctly... so it seems like google-java-format does not do this correctly.

**Comment by PhilippWendler** [comment] 2021-05-26 15:33
cf. #51

**Comment by cushon** [comment] 2021-05-26 16:52
This is a duplicate of #51

**Closed by cushon** 2021-05-26 16:52 UTC
