### ISSUE TITLE
can you compile the plugin with java 1.8?

### ISSUE THREAD

**Issue by jiqimaogou** [google/google-java-format#570] opened 2021-03-05 12:51 UTC
can you compile the plugin with java 1.8?

it can not work in android studio 4.2. the android studio internal jdk is 1.8.

```
Caused by: com.intellij.diagnostic.PluginException: While loading class com.google.googlejavaformat.intellij.InitialConfigurationProjectManagerListener: com/google/googlejavaformat/intellij/InitialConfigurationProjectManagerListener has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: google-java-format]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:262)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:205)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:113)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:713)
	... 102 more
```

if I do not use jdk 8, use jdk 11 instead, android studio have some issue.

**Comment by tbroyer** [comment] 2021-03-05 13:07
Duplicate of #536 
And no, it cannot "just" be compiled with JDK 8. GJF requires JDK 11 since 1.9; you can downgrade to 1.8 though.
https://github.com/google/google-java-format/issues/536#issuecomment-716517299

**Closed** 2021-03-05 19:48 UTC
