### ISSUE TITLE
Not working with IntelliJ 2017.3.1

### ISSUE THREAD

**Issue by hsingh** [google/google-java-format#236] opened 2017-12-20 16:18 UTC
I'm using IntelliJ 2017.3.1 and plugin version 1.5.0.173. The plugin is enabled for the project but currently selected code style scheme always overrides google-java-format. 

Is this a known issue?

**Comment by hsingh** [comment] 2017-12-20 20:51
It seems to work consistently as long as you don't select the "Default" IDE check style.

**Comment by chengniansun** [comment] 2017-12-21 19:14
I can confirm that it does not work.

**Comment by sormuras** [comment] 2017-12-21 19:17
Works like a charm on:

```
IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.17, built on December 19, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by peavers** [comment] 2018-01-30 03:33
Can confirm works perfectly on 
```
IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 16, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
```

**Comment by jacobk** [comment] 2018-02-21 09:04
Doesn't work for me neither. 

Should the built in "Code Style" settings be completely overridden by this plugin? It seems like whatever I pick there is used instead of the `google-java-format` which is enabled for the project.

```
IntelliJ IDEA 2017.3.4 (Community Edition)
Build #IC-173.4548.28, built on January 30, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6
```

**Comment by aaime** [comment] 2018-03-24 16:20
Having the same issue as @jacobk intellij format action keeps on adding spaces between (non static) imports starting with java and then the maven plugin reports a failure. E.g.:

````
import org.opengis.parameter.ParameterDescriptor;
import org.opengis.parameter.ParameterValue;
import org.opengis.referencing.crs.CoordinateReferenceSystem;
import org.opengis.referencing.datum.PixelInCell;
import org.opengis.referencing.operation.MathTransform;

import javax.imageio.spi.ImageReaderSpi;
import javax.media.jai.ImageLayout;
import java.awt.Rectangle;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
````

**Comment by therealppa** [comment] 2018-03-27 08:35
@aaime I had to add an additional step:

1. Enable the formatter plugin
2. Copy "Default" scheme into project
3. Go into "Imports" 
4. Set "Class count to use import with '*'" and "Name count to use static import with '*'" to 999
5. scroll down to "Import layout", set it to:
- Import static all other imports
- Blank line
- import all other imports

I feel that the imports were automatically correct in past versions of IntelliJ and the plugin...

**Comment by plumpy** [comment] 2018-06-04 20:13
Duplicate of #94

**Closed** 2018-06-04 20:18 UTC
Labels: IntelliJ

**Comment by kraphaelmagnite** [comment] 2023-07-18 23:46
Note that this is still occurring for me exactly as described above with plugin version 1.16.0.2 . it seems like the import settings aren't being respected at all. tried steps above as well which did not change anything. any ideas what could be going on please? thanks!


```IntelliJ IDEA 2023.1.4 (Community Edition)
Build #IC-231.9225.16, built on July 11, 2023
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.4.1
```
