### ISSUE TITLE
can not install in android studio 3.0,3.0.1

### ISSUE THREAD

**Issue by treanow** [google/google-java-format#278] opened 2018-04-27 16:42 UTC
<img width="464" alt="default" src="https://user-images.githubusercontent.com/13456586/39374130-6b6e2352-4a7c-11e8-86b6-736f8816945a.png">

if I install from disk
<img width="410" alt="default" src="https://user-images.githubusercontent.com/13456586/39374176-92ca00b0-4a7c-11e8-9bc8-59f3c541387b.png">

if I install from BrowseRepositories, when I restart AS
<img width="979" alt="default" src="https://user-images.githubusercontent.com/13456586/39374295-fdb586ba-4a7c-11e8-9ed3-19bd568f445f.png">

How should I do ?

**Comment by liangjingkanji** [comment] 2018-04-30 13:43
me too

**Comment by liangjingkanji** [comment] 2018-04-30 13:49
这个插件格式化注释, 真是该死的. 打乱了我优雅的注释
但是这个插件注释是最完善的. 就是动不动就崩溃crash

**Comment by plumpy** [comment] 2018-04-30 13:50
Duplicate of #274

**Closed by plumpy** 2018-04-30 13:50 UTC
