### ISSUE TITLE
Use @formatter:off and @formatter:on with google-java-format

### ISSUE THREAD

**Issue by kryczaatos** [google/google-java-format#295] opened 2018-07-18 07:42 UTC
I would like to exclude some of the code blocks from default formatting approach. I used to use **@formatter:on and off** for that, but it seems that it doesn't work with google-java-format.
Is there is any way to use it?

**Comment by jbduncan** [comment] 2018-07-18 09:52
Hi @kryczaatos. Sadly, I believe that it's both unsupported and an explicit non-goal of google-java-format to allow users to exclude code blocks from formatting, but I'm sure that someone on the google-java-format team can either correct me or clarify.

**Comment by jbduncan** [comment] 2018-07-18 09:52
@kryczaatos I don't know what your situation is or why you want to exclude certain code blocks, but if you want to format some code just a bit differently, e.g. if google-java-format gives you a long-ish line like this, but you want it split into multiple lines:

```java
List<String> strings = numbers.stream().map(Object::toString).collect(toList());
```

then if you simply insert a blank comment as so:

```java
List<String> strings = numbers //
.stream().map(Object::toString).collect(toList());
```

then when you next run google-java-format, it will format it like this:

```java
List<String> strings = 
    numbers //
        .stream()
        .map(Object::toString)
        .collect(toList());
```

It's a weird workaround, but I've found it to be quite useful, personally.

I hope this helps!

**Comment by cushon** [comment] 2018-07-23 18:56
This is a duplicate of #137.

**Closed by cushon** 2018-07-23 18:56 UTC
