### ISSUE TITLE
Local classes produce - error: generated extra token ";"

### ISSUE THREAD

**Issue by rbellamy** [google/google-java-format#28] opened 2016-02-28 22:51 UTC
Local classes generate a `error: generated extra token ";"` error and the file fails to be formatted.

Yes, I'm aware this isn't a healthy pattern, but it's what I have and barring a refactor I'm stuck with it for now. It is valid Java and I'm pretty sure the formatter shouldn't choke on it.

```
// some stuff
} else if (command.equals("Some command")) {
  JDialog dialog = new JDialog(this, "Launching Some command...");
  class ProgressWorker<JDialog,String> extends ProgressSwingWorker {
    public ProgressWorker(javax.swing.JDialog dialog,
        java.lang.String title) {
      super(dialog, title);
    }

    @Override
    public Object construct() {
      // TODO Auto-generated method stub
      return null;
    }
  }; // <=== this is the token that the formatter chokes on
  // some more stuff
```

**Comment by cushon** [comment] 2016-02-28 23:44
The issue is the unnecessary `;` after the local class declaration. Removing it works around the bug.

This was fixed by c3a34b8c9b12dfc833fb0fc4a04d4732e62de91f, so it'll work after the next release.

**Closed by cushon** 2016-02-28 23:44 UTC
