### ISSUE TITLE
Feature Request: Intellij Plugin to Allow Excluding Formatting by file pattern or package

### ISSUE THREAD

**Issue by navaneeth-spotnana** [google/google-java-format#457] opened 2020-04-20 12:48 UTC
I have some autogenerated code that I wish not to format. Is it possible to disable the plugin for a package, or for a file pattern?

**Comment by plumpy** [comment] 2020-06-26 17:34
Thanks for the request, marking this as a duplicate of #437

**Closed by plumpy** 2020-06-26 17:34 UTC
Labels: IntelliJ
