### ISSUE TITLE
impositive inline annotation for class fields

### ISSUE THREAD

**Issue by mrodriguezrPSL** [google/google-java-format#304] opened 2018-08-24 16:48 UTC
the documentation says "There are no specific rules for formatting annotations on parameters, local variables, or types." so why the plugin override the default user configuration about annotations to make it inline?
there should be an option to avoid this issue.

**Comment by cushon** [comment] 2019-04-18 03:47
I think this is a duplicate of #360.

**Closed by cushon** 2019-04-18 03:47 UTC
