### ISSUE TITLE
4.1.1 Braces are used where optional not implemented

### ISSUE THREAD

**Issue by galvanopus** [google/google-java-format#435] opened 2020-01-24 21:22 UTC
Input:
```java
int a = 0;
if (2 < 3) a++;
System.out.println(a);
```

Expected:
```java
int a = 0;
if (2 < 3) {
  a++;
}
System.out.println(a);
```

Actual:
```java
int a = 0;
if (2 < 3) a++;
System.out.println(a);
```

**Comment by lucasbraune** [comment] 2020-04-24 03:25
I am working on this issue.

**Comment by navaneeth-spotnana** [comment] 2020-04-28 05:51
@lucasbraune That's great news.  The issue is there on java 11 too.

**Comment by anthonyvdotbe** [comment] 2020-04-28 06:01
@galvanopus this can be closed as a duplicate of #51

**Comment by cushon** [comment] 2020-04-28 07:23
#51

**Closed by cushon** 2020-04-28 07:23 UTC
Labels: non-whitespace
