### ISSUE TITLE
Formatter not adding a blank line between copyright/license information and package statement

### ISSUE THREAD

**Issue by Zopsss** [google/google-java-format#1148] opened 2024-08-23 15:46 UTC
Detected at @checkstyle : https://github.com/checkstyle/checkstyle/pull/15548#discussion_r1728819185

[3 Source file structure](https://google.github.io/styleguide/javaguide.html#s3-source-file-structure) rule says:

```
A source file consists of, in order:

1. License or copyright information, if present
2. Package statement
3. Import statements
4. Exactly one top-level class

Exactly one blank line separates each section that is present.
```

Based on this rule, the copyright/license information section and package statement should have one blank line between them. But google-java-format does not add a blank line between them, for example:

```
$ cat .\TestingPackageSeparation.java
///////////////////////////////////////////////////////////////////////////////////////////////
// checkstyle: Checks Java source code and other text files for adherence to a set of rules.
//
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
///////////////////////////////////////////////////////////////////////////////////////////////
package com.google.checkstyle.test.chapter3filestructure.rule3sourcefile;

public class TestingPackageSeparation {}

$ java -jar .\google-java-format-1.23.0-all-deps.jar .\TestingPackageSeparation.java > TestingPackageSeparationUpdated.java

$ cat .\TestingPackageSeparationUpdated.java
///////////////////////////////////////////////////////////////////////////////////////////////
// checkstyle: Checks Java source code and other text files for adherence to a set of rules.
//
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
///////////////////////////////////////////////////////////////////////////////////////////////
package com.google.checkstyle.test.chapter3filestructure.rule3sourcefile;

public class TestingPackageSeparation {}

$ git diff TestingPackageSeparation.java TestingPackageSeparationUpdated.java 
```

There's no diff between the original file and formatted file, the formatted file should have added a blank line between package statement and copyright/license information.

**Comment by cushon** [comment] 2024-08-24 00:00
This is a duplicate of https://github.com/google/google-java-format/issues/434

**Closed by cushon** 2024-08-24 00:00 UTC
