### ISSUE TITLE
Before commit reformatting option in IntelliJ does invoke plugin

### ISSUE THREAD

**Issue by mqzry** [google/google-java-format#228] opened 2017-11-27 15:57 UTC
I have the IntelliJ plugin installed and reformatting works as expected. If I select 'Reformat code' option in commit window, then it will take my currently selected Code Style sheet and not use google-java-format.  It sets indentation to 4 spaces instead of 2 for example. Reformatting after committing then immediately gives local changes.

Is this a known issue? Will this be solved?

**Comment by mqzry** [comment] 2018-01-17 19:03
What's the status? Should I try to fix it myself?

**Comment by plumpy** [comment] 2018-06-04 21:09
Hey there,

I tried to reproduce this, but was not able to. It's very old, though, so maybe it got fixed in some interim version.

Can you still reproduce it? What version of the plugin do you have and what version of the IDE?

Thanks and sorry for the delay...

**Comment by codahale** [comment] 2018-06-04 22:10
This is still a problem with 1.6.0 of the plugin and the latest version of IntelliJ (2018.1.4/IU-181.5087.20).

To reproduce:

1. Enter some malformatted code into a file.
2. Commit the change with the _Reformat code_ checkbox enabled.
3. The code will not be changed.
4. Run _Reformat Code_ from the _Code_ menu.
5. The code will be changed.

**Comment by mqzry** [comment] 2018-06-16 20:15
I tried it out again and it seems to be fixed.
My setup is:
IntelliJ @ IU-173.4548.28
google-java-format plugin @ 1.6.0

**Comment by codahale** [comment] 2018-06-16 20:29
To reproduce:

1. Change a project’s Java code style to the IntelliJ default.
2. Join a series of statements in a class on a single line.
3. Commit the code, making sure the _Reformat code_ checkbox is checked.
4. Observe that the changed code was refomatted using the default IntelliJ style

**Comment by rymach** [comment] 2018-07-30 19:12
I'm also seeing this issue (version 1.6.1 of the plugin)

**Comment by alexbde** [comment] 2018-08-06 14:38
We're also experiencing this issue. Is there any progress on this?

Reproducable on Windows 7 and macOS 10.13 with IntelliJ IDEA 2017.3, 2018.1 and 2018.2 using plugin 1.5.0 and 1.6.1.

**Comment by YanzheL** [comment] 2019-03-31 02:45
Same issue with IntelliJ 2019.1 (IU-191.6183.87), google-java-format  v1.7.0.1
Environment:
1. macOS 10.14.3, openjdk-8 and openjdk-11
2. Ubuntu 18.04 LTS, openjdk-8 and openjdk-11

**Comment by YanzheL** [comment] 2019-03-31 02:50
It has been two years since this issue was posted, any progress?

**Comment by mleonhard** [comment] 2019-05-01 03:56
Please fix.

IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
google-java-format v1.7.0.1

**Comment by mleonhard** [comment] 2019-05-01 04:09
I really wish I could use the automatic formatter.

IntelliJ IDEA 2019.1.1 (Community Edition)
Build #IC-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
google-java-format v1.7.0.1

@plumpy Please fix?  This issue and #264 are assigned to you and have been ignored for 2 years.

**Comment by YanzheL** [comment] 2019-05-01 05:47
My current workaround is to use XML based [intellij-java-google-style](https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml) file instead of this google-java-format plugin.

It works fine, but the formatted code is slightly different from the output of this plugin.

**Comment by alexbde** [comment] 2019-06-05 11:36
@YanzheL We're doing the same as workaround. We used plugin google-java-format for a while but not being able to use before commit action is confusing and frustrating our developers. This is a show stopper for us.

Last tested on
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by krasa** [comment] 2019-10-16 21:19
This should be just a matter of overriding `  public void reformatTextWithContext(PsiFile psiFile, ChangedRangesInfo changedRangesInfo)`

**Comment by denniseffing** [comment] 2020-07-14 08:47
Are there any plans to support this in the future?

**Comment by stonelazy** [comment] 2020-07-20 05:22
Am having this exact same issue, any work arounds possible ? We face many merge conflicts due to this.

**Comment by Tommy544** [comment] 2020-11-23 09:45
I am having the same issue, any update on this?

**Comment by Agraphie** [comment] 2020-11-27 16:20
Also observing the same issue. The workaround with the codestyle.xml is nice, but the formatting can be wildly different. Especially regarding annotations (on single line, annotation indentation, ...) so the workaround is in the end not really sufficient as you still have to always apply the style either manually or via a maven plugin.

**Closed** 2021-01-27 17:07 UTC
Labels: IntelliJ

**Comment by vshamrai** [comment] 2024-02-22 09:02
We faced the same issue. Can we expect that it will be fixed?
