### ISSUE TITLE
Publish https://github.com/google/google-java-format/releases/download/google-java-format-1.7/google-java-format-eclipse-plugin_1.7.0.jar

### ISSUE THREAD

**Issue by elharo** [google/google-java-format#353] opened 2019-03-14 12:41 UTC
https://github.com/google/google-java-format/releases/download/google-java-format-1.7/google-java-format-eclipse-plugin_1.7.0.jar

**Comment by KWottrich** [comment] 2019-05-20 17:50
This is a duplicate of #331

**Closed** 2019-05-20 17:56 UTC
Labels: Eclipse
