### ISSUE TITLE
GJF intellij plugin does not format files with Java 14 switch expressions

### ISSUE THREAD

**Issue by abrudin** [google/google-java-format#455] opened 2020-04-15 18:42 UTC
When using a Java 14 switch expression in a Java source file (for example a badly formatted one like):
```
final TestEnum te = TestEnum.TEST1;
    final String s = switch (te) {
          case TEST1 -> "hej";
              case TEST2 -> "nej";
      };
```
the file does not get formatted at all when using the google-java-format plugin, whereas files without this kind of expressions work flawlessly.

This issue is present in Intellij 2020.1 with the latest google-java-format 1.7.0.5.

There was no exceptions and I found no logs, Ctrl-Alt-L just said that there was no lines changed, code already properly formatted. I tried launching Intellij with Java 14 as well, but to no avail.

**Comment by sormuras** [comment] 2020-04-15 18:51
Duplicate of #436 ... which is already solved on `master` via https://github.com/google/google-java-format/commit/4ddb9148c103b9c65768e519884b0c8ad5caaf39

**Comment by cushon** [comment] 2020-04-26 22:48
#436

**Closed by cushon** 2020-04-26 22:48 UTC
