### ISSUE TITLE
Inconsistent formatting between eclipse and IntelliJ

### ISSUE THREAD

**Issue by aharonha** [google/google-java-format#381] opened 2019-06-20 15:24 UTC
Hey.
My team is working without specified IDE, so some of us use eclipse (as I do) and others are using IntelliJ.
After a CI build that indeed passed checkstyle validations (using `mvn-checkstyle-plugin`) the other guys told me that they had to re-format the source once again.

This issue goes even more complicated. As I run this command:
`find . -name "*.java" | xargs -n5 -L5 -P5 -i java -jar ~/Downloads/google-java-format-1.7-all-deps.jar --replace {}` 
￼I see in `git status` that files have changed. This changed files seems OK to my teammates!

**Comment by tbroyer** [comment] 2019-06-20 15:49
See also https://github.com/google/google-java-format/issues/19#issuecomment-502464854

If you settled on Google Java Format, then use it in your Maven build too (see https://github.com/google/google-java-format#third-party-integrations) instead of Checkstyle.

**Comment by wacaine** [comment] 2019-06-27 14:34
If you have not solved your issue yet. It may be because IntelliJ is using 1.7 and the eclipse plugin is only 1.6 .  see this ticket . https://github.com/google/google-java-format/issues/331

**Comment by cushon** [comment] 2019-12-19 01:50
Closing as a dupe of #331.

**Closed by cushon** 2019-12-19 01:50 UTC
