### ISSUE TITLE
Saving and formatting removes all breakpoints on the saved file using Eclipse

### ISSUE THREAD

**Issue by romulodiniz** [google/google-java-format#537] opened 2020-10-22 23:54 UTC
Hello everyone,
is it just me or the save and format action removes all existing breakpoints on the formatted class? I'm using Eclipse Version 2020-03 (4.15.0) and this happens all the times I format it.

**Comment by tobous** [comment] 2020-12-23 03:17
Duplicate of #317.

**Closed** 2021-01-12 00:20 UTC
Labels: Eclipse
