### ISSUE TITLE
How to ignore javadoc format?

### ISSUE THREAD

**Issue by TYZRPVX** [google/google-java-format#329] opened 2019-01-04 12:40 UTC
```
/**
     * Pushes a message onto the end of the message queue after all pending messages
     * before the current time. It will be received in {@link #handleMessage},
     * in the thread attached to this handler.
     *
     * @return Returns true if the message was successfully placed in to the
     *         message queue.  Returns false on failure, usually because the
     *         looper processing the message queue is exiting.
     */
```

I may write some javadoc like this, but formatter may separate line again. So, how to ignore javadoc format?

**Comment by cushon** [comment] 2019-04-18 04:24
This is a duplicate of #139.

**Closed by cushon** 2019-04-18 04:24 UTC
