### ISSUE TITLE
allow running gjf as test

### ISSUE THREAD

**Issue by hanwen** [google/google-java-format#140] opened 2017-03-21 12:15 UTC
it would be great if GJF could be run in a --test mode, where exit status 1 means: file was reformatted.

Background: I'm trying to write a Bazel rule that checks that the Gerrit source code is well-formatted, and this would slightly simplify my life.

**Comment by sormuras** [comment] 2017-03-21 12:18
Duplicate of #105 (with PR #106)

**Closed** 2017-10-10 04:51 UTC
