### ISSUE TITLE
Java 17 Pattern Matching for Switch (JEP-406) compatibility issue

### ISSUE THREAD

**Issue by mcwhitak** [google/google-java-format#684] opened 2021-11-09 17:34 UTC
With version `1.12.0` `google-java-format` does not properly recognize imports utilized only during pattern matched switches.

As an example, for the following hierarchy
```java
package example.model;

public sealed interface SealedInterface {}

public non-sealed interface TypeA {}
public non-sealed interface TypeB {}
```
and a Java file using this hierarchy with a pattern matched switch

```java
package example;

import example.model.SealedInterface;
import example.model.TypeA;
import example.model.TypeB;

public class Main {
  public void apply(SealedInterface sealedInterface) {
    switch(sealedInterface) {
      case TypeA a -> System.out.println("A!");
      case TypeB b -> System.out.println("B!");
    }
  }
}
```
`google-java-format` will flag `import example.model.TypeA` and `import example.model.TypeB` as unused and candidates for removal.

I've recreated this bug in a [small repo](https://github.com/mcwhitak/java-17-gojf-bug) that illustrates the issue.

**Comment by lorenzleutgeb** [comment] 2021-11-19 08:57
This appears to be a duplicate of #683

**Comment by cushon** [comment] 2021-11-19 22:25
This is fixed now: the formatter didn't support pattern matching in switches on Java 17 at all, and there was a separate issue specifically about unused imports. Thanks for the report!

**Closed by cushon** 2021-11-19 22:25 UTC
